# Generated by Django 3.1.4 on 2020-12-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('total_budget', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('status', models.CharField(choices=[('NEW', '申请已提交，等待审核'), ('INTERNAL_ACCEPT', '内部审核通过'), ('THIRD_PARTY', '材料已发给第三方公司'), ('SUCCESS', '第三方公司金额已发放'), ('FAILED', '申请失败')], default='NEW', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
        ),
    ]
